hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true

# \ud83d\udfe2 1. S\u1eeda d\u1ea5u g\u1ea1ch d\u01b0\u1edbi th\u00e0nh driverClass chu\u1ea9n c\u00fa ph\u00e1p Java
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver

# \ud83d\udfe2 2. Gi\u1eef nguy\u00ean URL Aiven chu\u1ea9n \u0111\u00e9t c\u1ee7a \u00f4ng gi\u00e1o
hibernate.connection.url=jdbc:mysql://travelvista-travelvista.h.aivencloud.com:28451/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
hibernate.connection.username=avnadmin
hibernate.connection.password=AVNS_ZAjV2-Q4hwp3poPcZ1E

# \ud83d\udfe2 3. C\u1ea5u h\u00ecnh Connection Pool m\u1eb7c \u0111\u1ecbnh c\u1ee7a Hibernate (N\u00e9 c\u1ea5u h\u00ecnh Hikari l\u1ed7i)
hibernate.connection.pool_size=10
hibernate.connection.autocommit=true

# \ud83d\udfe2 4. C\u00e0i \u0111\u1eb7t th\u1eddi gian t\u1ef1 h\u1ee7y n\u1ebfu k\u1ebft n\u1ed1i treo (Qu\u00e1 5 gi\u00e2y \u0111\u00e9o \u0111\u01b0\u1ee3c l\u00e0 ng\u1eaft \u0111\u1ec3 b\u00e1o l\u1ed7i lu\u00f4n, n\u00e9 vi\u1ec7c b\u1ecb treo l\u1ef3 l\u00e0m Render Timed Out)
hibernate.c3p0.timeout=5000