hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver

hibernate.connection.url=jdbc:mysql://travelvista-travelvista.h.aivencloud.com:28451/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
hibernate.connection.username=avnadmin
hibernate.connection.password=AVNS_ZAjV2-Q4hwp3poPcZ1E
