hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true

hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver

hibernate.connection.url=jdbc:mysql://travelvista-travelvista.h.aivencloud.com:28451/defaultdb?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
hibernate.connection.username=avnadmin
hibernate.connection.password=AVNS_ZAjV2-Q4hwp3poPcZ1E

hibernate.connection.pool_size=10
hibernate.connection.autocommit=true
hibernate.c3p0.timeout=5000

hibernate.temp.use_jdbc_metadata_defaults=false
hibernate.hbm2ddl.auto=none
